---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: dns-dc1
spec:
  selector:
    app: minio
  ports:
    - name: s3
      port: 9000
      targetPort: 9000
    - name: console
      port: 9001
      targetPort: 9001
---
apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
  namespace: dns-dc1
type: Opaque
stringData:
  root-user: minioadmin
  root-password: minioadmin123
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data
  namespace: dns-dc1
spec:
  accessModes: [ReadWriteOnce]
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: dns-dc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: vks-hoanq3-maas-dev-nodegroup-d43eb-1536b
      containers:
        - name: minio
          image: quay.io/minio/minio:latest
          args: [server, /data, --console-address, ":9001"]
          ports:
            - containerPort: 9000
              hostPort: 9000
            - containerPort: 9001
              hostPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-password
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: minio-data
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-setup
  namespace: dns-dc1
spec:
  ttlSecondsAfterFinished: 300
  template:
    spec:
      hostNetwork: true
      restartPolicy: OnFailure
      nodeSelector:
        kubernetes.io/hostname: vks-hoanq3-maas-dev-nodegroup-d43eb-1536b
      initContainers:
        - name: wait
          image: busybox:1.36
          command: [sh, -c, "until wget -q --spider http://127.0.0.1:9000/minio/health/ready; do sleep 5; done"]
      containers:
        - name: setup
          image: quay.io/minio/mc:latest
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-user
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: root-password
          command:
            - /bin/sh
            - -c
            - |
              mc alias set local http://127.0.0.1:9000 $MINIO_ROOT_USER $MINIO_ROOT_PASSWORD
              mc mb local/lightning-stream --ignore-existing
              mc version enable local/lightning-stream
              echo "MinIO DC1 setup complete"
