apiVersion: v1
kind: Service
metadata:
  annotations:
    strimzi.io/discovery: |-
      [ {
        "port" : 9092,
        "tls" : false,
        "protocol" : "kafka",
        "auth" : "none"
      }, {
        "port" : 9093,
        "tls" : true,
        "protocol" : "kafka",
        "auth" : "none"
      } ]
  labels:
    app.kubernetes.io/instance: cluster-dc1
    app.kubernetes.io/managed-by: strimzi-cluster-operator
    app.kubernetes.io/name: kafka
    app.kubernetes.io/part-of: strimzi-cluster-dc1
    strimzi.io/cluster: cluster-dc1
    strimzi.io/component-type: kafka
    strimzi.io/discovery: "true"
    strimzi.io/kind: Kafka
    strimzi.io/name: cluster-dc1-kafka
  name: cluster-dc1-kafka-bootstrap
  namespace: active-passive
  ownerReferences:
  - apiVersion: kafka.strimzi.io/v1beta2
    blockOwnerDeletion: false
    controller: false
    kind: Kafka
    name: cluster-dc1
    uid: c606d459-408a-4e27-bdda-29746cd7c58f
spec:
  clusterIP: 10.254.65.112
  clusterIPs:
  - 10.254.65.112
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: tcp-replication
    port: 9091
    protocol: TCP
    targetPort: 9091
  - name: tcp-clients
    port: 9092
    protocol: TCP
    targetPort: 9092
  - name: tcp-clientstls
    port: 9093
    protocol: TCP
    targetPort: 9093
  selector:
    strimzi.io/cluster: cluster-dc1
    strimzi.io/kind: Kafka
    strimzi.io/name: cluster-dc1-kafka
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
