---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dns-dc1
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
      server {
        listen 8080;
        location / {
          default_type application/json;
          return 200 '{"dc": "DC1", "ip": "10.0.1.10", "message": "Hello from DC1"}';
        }
        location /health {
          return 200 'OK';
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dns-dc1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: backend
          image: nginx:alpine
          ports:
            - containerPort: 8080
              hostPort: 8080
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: backend-config
