---
apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: dns-dc2
data:
  nginx.conf: |
    events { worker_connections 1024; }
    http {
      server {
        listen 8180;
        location / {
          default_type application/json;
          return 200 '{"dc": "DC2", "ip": "10.0.2.10", "message": "Hello from DC2"}';
        }
        location /health {
          return 200 'OK';
        }
      }
    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: dns-dc2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      nodeSelector:
        kubernetes.io/hostname: vks-hoanq3-maas-dev-nodegroup-d43eb-d9b4c
      containers:
        - name: backend
          image: nginx:alpine
          ports:
            - containerPort: 8180
              hostPort: 8180
          volumeMounts:
            - name: config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
          livenessProbe:
            httpGet:
              path: /health
              port: 8180
            initialDelaySeconds: 5
            periodSeconds: 10
      volumes:
        - name: config
          configMap:
            name: backend-config
