
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-yml
  labels:
    app: logstash-yml
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    path.config: /usr/share/logstash/config/conf.d
    pipeline.workers: 4
    pipeline.batch.size: 1000

---
kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-loghub
data:
  logtash.conf: |-
    input {
      kafka {
        codec => json
        bootstrap_servers=>"${BOOTSTRAP_SERVERS}"
        topics_pattern => ".*${TOPIC}.*"
        decorate_events => "true"
        auto_offset_reset => "latest"
        group_id => "${GROUP}"
        consumer_threads => "${THREADS}"
        client_id => "${HOSTNAME}"
        metadata_max_age_ms => 20000
      }
    }
    output {
      elasticsearch {
        codec => json
        hosts => ["${ES_HOST}"]
        http_compression => true
        index => "${INDEX_PREFIX}_%{+YYYY.MM.dd}"
        user => "${USER_ES}"
        password => "${PASSWORD_ES}"
      }
    }

#  logtash.conf: |-
#    input {
#      kafka {
#        codec => json
#        bootstrap_servers=>"${BOOTSTRAP_SERVERS}"
#        topics => ["${TOPIC}"]
#        decorate_events => "true"
#        auto_offset_reset => "latest"
#        group_id => "${GROUP}"
#        consumer_threads => "${THREADS}"
#        client_id => "${HOSTNAME}"
#        security_protocol => "SSL"
#        ssl_truststore_location => "/usr/share/logstash/kafkacert/vng.trust"
#        ssl_truststore_password => "${TRUSTSTORE_PASS}"
#        ssl_keystore_location => "/usr/share/logstash/kafkacert/user.key"
#        ssl_keystore_password => "${KEYSTORE_PASS}"
#        ssl_key_password => "${KEYSTORE_PASS}"
#        ssl_endpoint_identification_algorithm => ""
#      }
#    }
#    output {
#      elasticsearch {
#        codec => json
#        hosts => ["${ES_HOST}"]
#        http_compression => true
#        index => "${INDEX_PREFIX}_%{+YYYY.MM.dd}"
#        user => "${USER_ES}"
#        password => "${PASSWORD_ES}"
#      }
#    }

---

kind: ConfigMap
apiVersion: v1
metadata:
  name: logstash-jvm
  # namespace: log-service
data:
  jvm.options: |
    # JVM configuration

    # Xms represents the initial size of total heap space
    # Xmx represents the maximum size of total heap space

    -Xms1g
    -Xmx1g

    ################################################################
    ## Expert settings
    ################################################################
    ##
    ## All settings below this section are considered
    ## expert settings. Don't tamper with them unless
    ## you understand what you are doing
    ##
    ################################################################

    ## GC configuration
    #-XX:+UnlockExperimentalVMOptions
    #-XX:+UseConcMarkSweepGC
    #-XX:CMSInitiatingOccupancyFraction=75
    #-XX:+UseCMSInitiatingOccupancyOnly
    #-XX:InitiatingHeapOccupancyPercent=75
    #-XX:InitiatingHeapOccupancyPercent=70
    #-XX:+UseG1GC
    #-XX:+UseZGC
    -XX:+UseParallelGC
    -XX:ActiveProcessorCount=4
    #-XX:GCTimeRatio=19
    #-XX:MaxGCPauseMillis=2


    ## Locale
    # Set the locale language
    #-Duser.language=en

    # Set the locale country
    #-Duser.country=US

    # Set the locale variant, if any
    #-Duser.variant=

    ## basic

    # set the I/O temp directory
    #-Djava.io.tmpdir=$HOME

    # set to headless, just in case
    -Djava.awt.headless=true

    # ensure UTF-8 encoding by default (e.g. filenames)
    -Dfile.encoding=UTF-8

    # use our provided JNA always versus the system one
    #-Djna.nosys=true

    # Turn on JRuby invokedynamic
    -Djruby.compile.invokedynamic=true
    # Force Compilation
    -Djruby.jit.threshold=0

    ## heap dumps

    # generate a heap dump when an allocation from the Java heap fails
    # heap dumps are created in the working directory of the JVM
    -XX:+HeapDumpOnOutOfMemoryError

    # specify an alternative path for heap dumps
    # ensure the directory exists and has sufficient space
    #-XX:HeapDumpPath=${LOGSTASH_HOME}/heapdump.hprof

    # GC logging
    #-XX:+PrintGCDetails
    #-XX:+PrintGCTimeStamps
    #-XX:+PrintGCDateStamps
    #-XX:+PrintClassHistogram
    #-XX:+PrintTenuringDistribution
    #-XX:+PrintGCApplicationStoppedTime

    # log GC status to a file with time stamps
    # ensure the directory exists
    #-Xloggc:/tmp/gc.log

    # Entropy source for randomness
    -Djava.security.egd=file:/dev/urandom
